Fix undefined reference to c99_vsnprintf and ts_utf8_sequence_length when using mingw32 gcc.
The mingw32 gcc compiler doesn't treat __inline as Visual C++ does.
Use `static inline` instead of `__inline` for c99_vsnprintf.
Don't use `__inline` for ts_utf8_sequence_length.